// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuzrEDkvROHsbLHchC8tPsauRtcTqrZSQ',
    appId: '1:735758556284:web:8499b7351d97c0b3b8bdf9',
    messagingSenderId: '735758556284',
    projectId: 'agro-app-6b445',
    authDomain: 'agro-app-6b445.firebaseapp.com',
    storageBucket: 'agro-app-6b445.appspot.com',
    measurementId: 'G-FBZ7K0479V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmWo9oTJNk_9TATxIsG_RoDWLEw1HbXzo',
    appId: '1:735758556284:android:b39efbf8934f4ae4b8bdf9',
    messagingSenderId: '735758556284',
    projectId: 'agro-app-6b445',
    storageBucket: 'agro-app-6b445.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqCdUzrkrzyFQ15N4u5GNBXPFq1UOBAI4',
    appId: '1:735758556284:ios:942c4c2272e24db7b8bdf9',
    messagingSenderId: '735758556284',
    projectId: 'agro-app-6b445',
    storageBucket: 'agro-app-6b445.appspot.com',
    iosClientId: '735758556284-hmdd7gifiv6g2kepbhsvrms0thvncrn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
